server:
  port: 8080

spring:
  main:
    web-application-type: reactive
  application:
    name: api-gateway
  mvc:
    servlet:
      load-on-startup: 1

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8001/eureka/
    registryFetchIntervalSeconds: 1
  instance:
    leaseRenewalIntervalInSeconds: 1

jwt:
  secret: MiAVzqUXy5Tfr1kVIGpPMiAVzqUXy5Tfr1kVIGpP
  expiration: 86400
