server:
  port: 9000

spring:
  application:
    name: data-analysis-service
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
  mvc:
    servlet:
      load-on-startup: 1

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8001/eureka/
    registryFetchIntervalSeconds: 1
  instance:
    leaseRenewalIntervalInSeconds: 1

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    enable:
      all: true
  health:
    show-details: always
  web:
    base-path: /actuator