server:
  port: 9000

spring:
  application:
    name: data-analysis-service
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: financial-data-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  mvc:
    servlet:
      load-on-startup: 1

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8001/eureka/
    registryFetchIntervalSeconds: 1
  instance:
    leaseRenewalIntervalInSeconds: 1

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    enable:
      all: true
  health:
    show-details: always
  web:
    base-path: /actuator
