management.endpoints.web.exposure.include: "*"

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: db
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest