server:
  port: 8001

spring:
  application:
    name: discovery-server
  eureka:
    client:
      registerWithEureka: false
      fetchRegistry: false
      service-url:
        defaultZone: http://discovery-server:8001/eureka/