spring:
  application:
    name: discovery-server

eureka:
  server:
    evictionIntervalTimerInMs: 3000
    response-cache-update-interval-ms: 3000
  client:
    registerWithEureka: false
    fetchRegistry: false
