server:
  port: 8001

spring:
  application:
    name: discovery-server
  eureka:
    client:
      registerWithEureka: false
      fetchRegistry: false
      service-url:
        defaultZone: http://discovery-server:8001/eureka/

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    enable:
      all: true
  health:
    show-details: always
  web:
    base-path: /actuator
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://tempo:9411/api/v2/spans
